name: schedule_app
description: 이미지에서 일정 정보를 추출해 구글/삼성 캘린더에 등록하는 앱
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  device_calendar: ^4.3.3
  timezone: ^0.9.4
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
